# Multivariable linear regression


## 1) 필요한 모듈을 import 합니다

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## 2) 학습 데이터셋을 정의합니다

In [48]:
x_train = torch.FloatTensor([[80, 85, 90], 
                            [50, 55, 60],
                            [70, 75, 80]])
y_train = torch.FloatTensor([[95], [65], [85]])

## 3) 클래스로 모델을 구성합니다

In [54]:
class MultivaribleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x):
        return self.linear(x)

## 4) model과 optimizer를 정의합니다

In [55]:
model = MultivaribleModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

## 5) torch의 manual seed를 고정시킵니다

In [56]:
torch.manual_seed(1)

## 6) for문을 돌면서 학습을 수행합니다

In [57]:
epochs = 50000

for epoch in range(1, epochs+1):
    prediction = model(x_train)
    
    loss = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 5000 == 0:
        params = list(model.parameters())
        w1 = params[0][0][0].item()
        w2 = params[0][0][0].item()
        w3 = params[0][0][0].item()
        b = params[1].item()
        
        print('{:5d}번째 출력 >>> w: {:.2f},{:.2f},{:.2f}, b: {:.2f}, loss: {:.2f}'.format(epoch, w1, w2, w3, b, loss.item()))

 5000번째 출력 >>> w: 0.51,0.51,0.51, b: 0.31, loss: 2.88
10000번째 출력 >>> w: 0.37,0.37,0.37, b: 0.33, loss: 2.14
15000번째 출력 >>> w: 0.25,0.25,0.25, b: 0.36, loss: 1.58
20000번째 출력 >>> w: 0.15,0.15,0.15, b: 0.38, loss: 1.17
25000번째 출력 >>> w: 0.06,0.06,0.06, b: 0.40, loss: 0.87
30000번째 출력 >>> w: -0.02,-0.02,-0.02, b: 0.41, loss: 0.65
35000번째 출력 >>> w: -0.09,-0.09,-0.09, b: 0.42, loss: 0.48
40000번째 출력 >>> w: -0.14,-0.14,-0.14, b: 0.43, loss: 0.36
45000번째 출력 >>> w: -0.19,-0.19,-0.19, b: 0.44, loss: 0.26
50000번째 출력 >>> w: -0.24,-0.24,-0.24, b: 0.45, loss: 0.20


# Full code

In [81]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

x_train = torch.FloatTensor([[10, 20, 30],
                            [20, 30, 40],
                            [30, 40, 50]])
y_train = torch.FloatTensor([[40, 50], [50, 60], [60, 70]])

class MultivariableModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 2)
        
    def forward(self, x):
        return self.linear(x)
    
model = MultivariableModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

epochs = 50000
for epoch in range(1, epochs+1):
    prediction = model(x_train)
    
    loss = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 5000 == 0:
        params = list(model.parameters())
        w1 = params[0][0][0].item()
        w2 = params[0][0][0].item()
        w3 = params[0][0][0].item()
        b1= params[1][0].item()
        b2 = params[1][1].item()
        
        print('{:5d}번째 출력 >>> w:{:.2f},{:.2f},{:.2f}, b:{:.2f},{:.2f}, loss:{:.4f}'.format(epoch, w1, w2, w3, b1, b2, loss.item()))
        
print('\n')
print('result >>>')
prediction = model(x_train)
result = list(prediction)
for r in result:
    print(r)

 5000번째 출력 >>> w:0.08,0.08,0.08, b:-0.42,-0.02, loss:15.0614
10000번째 출력 >>> w:-0.29,-0.29,-0.29, b:-0.39,0.02, loss:4.0969
15000번째 출력 >>> w:-0.48,-0.48,-0.48, b:-0.37,0.04, loss:1.1145
20000번째 출력 >>> w:-0.58,-0.58,-0.58, b:-0.37,0.05, loss:0.3032
25000번째 출력 >>> w:-0.63,-0.63,-0.63, b:-0.36,0.05, loss:0.0826
30000번째 출력 >>> w:-0.66,-0.66,-0.66, b:-0.36,0.06, loss:0.0225
35000번째 출력 >>> w:-0.68,-0.68,-0.68, b:-0.36,0.06, loss:0.0061
40000번째 출력 >>> w:-0.68,-0.68,-0.68, b:-0.36,0.06, loss:0.0017
45000번째 출력 >>> w:-0.69,-0.69,-0.69, b:-0.36,0.06, loss:0.0005
50000번째 출력 >>> w:-0.69,-0.69,-0.69, b:-0.36,0.06, loss:0.0001


result >>>
tensor([39.9860, 49.9820], grad_fn=<SelectBackward>)
tensor([49.9976, 59.9969], grad_fn=<SelectBackward>)
tensor([60.0092, 70.0118], grad_fn=<SelectBackward>)
